name: Build and Deploy
on:
  push:
    branches:
      - Blog
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          bundle install
          bundle exec jekyll serve

      - name: Deploy
        uses: jamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: Blog
          folder: _site